package com.drew.metadata.exif;

import com.drew.metadata.Directory;
import java.util.HashMap;

public abstract class ExifDirectoryBase
  extends Directory
{
  public static final int TAG_35MM_FILM_EQUIV_FOCAL_LENGTH = 41989;
  public static final int TAG_APERTURE = 37378;
  public static final int TAG_APPLICATION_NOTES = 700;
  public static final int TAG_ARTIST = 315;
  public static final int TAG_BATTERY_LEVEL = 33423;
  public static final int TAG_BITS_PER_SAMPLE = 258;
  public static final int TAG_BODY_SERIAL_NUMBER = 42033;
  public static final int TAG_BRIGHTNESS_VALUE = 37379;
  public static final int TAG_CAMERA_OWNER_NAME = 42032;
  public static final int TAG_CFA_PATTERN = 41730;
  public static final int TAG_CFA_PATTERN_2 = 33422;
  public static final int TAG_CFA_REPEAT_PATTERN_DIM = 33421;
  public static final int TAG_COLOR_SPACE = 40961;
  public static final int TAG_COMPONENTS_CONFIGURATION = 37121;
  public static final int TAG_COMPRESSED_AVERAGE_BITS_PER_PIXEL = 37122;
  public static final int TAG_COMPRESSION = 259;
  public static final int TAG_CONTRAST = 41992;
  public static final int TAG_COPYRIGHT = 33432;
  public static final int TAG_CUSTOM_RENDERED = 41985;
  public static final int TAG_DATETIME = 306;
  public static final int TAG_DATETIME_DIGITIZED = 36868;
  public static final int TAG_DATETIME_ORIGINAL = 36867;
  public static final int TAG_DEVICE_SETTING_DESCRIPTION = 41995;
  public static final int TAG_DIGITAL_ZOOM_RATIO = 41988;
  public static final int TAG_DOCUMENT_NAME = 269;
  public static final int TAG_EXIF_IMAGE_HEIGHT = 40963;
  public static final int TAG_EXIF_IMAGE_WIDTH = 40962;
  public static final int TAG_EXIF_VERSION = 36864;
  public static final int TAG_EXPOSURE_BIAS = 37380;
  public static final int TAG_EXPOSURE_INDEX = 41493;
  public static final int TAG_EXPOSURE_INDEX_TIFF_EP = 37397;
  public static final int TAG_EXPOSURE_MODE = 41986;
  public static final int TAG_EXPOSURE_PROGRAM = 34850;
  public static final int TAG_EXPOSURE_TIME = 33434;
  public static final int TAG_FILE_SOURCE = 41728;
  public static final int TAG_FILL_ORDER = 266;
  public static final int TAG_FLASH = 37385;
  public static final int TAG_FLASHPIX_VERSION = 40960;
  public static final int TAG_FLASH_ENERGY = 41483;
  public static final int TAG_FLASH_ENERGY_TIFF_EP = 37387;
  public static final int TAG_FNUMBER = 33437;
  public static final int TAG_FOCAL_LENGTH = 37386;
  public static final int TAG_FOCAL_PLANE_RESOLUTION_UNIT = 41488;
  public static final int TAG_FOCAL_PLANE_X_RESOLUTION = 41486;
  public static final int TAG_FOCAL_PLANE_X_RESOLUTION_TIFF_EP = 37390;
  public static final int TAG_FOCAL_PLANE_Y_RESOLUTION = 41487;
  public static final int TAG_FOCAL_PLANE_Y_RESOLUTION_TIFF_EP = 37391;
  public static final int TAG_GAIN_CONTROL = 41991;
  public static final int TAG_GAMMA = 42240;
  public static final int TAG_HOST_COMPUTER = 316;
  public static final int TAG_IMAGE_DESCRIPTION = 270;
  public static final int TAG_IMAGE_HEIGHT = 257;
  public static final int TAG_IMAGE_HISTORY = 37395;
  public static final int TAG_IMAGE_NUMBER = 37393;
  public static final int TAG_IMAGE_UNIQUE_ID = 42016;
  public static final int TAG_IMAGE_WIDTH = 256;
  public static final int TAG_INTERLACE = 34857;
  public static final int TAG_INTEROP_INDEX = 1;
  public static final int TAG_INTEROP_VERSION = 2;
  public static final int TAG_INTER_COLOR_PROFILE = 34675;
  public static final int TAG_IPTC_NAA = 33723;
  public static final int TAG_ISO_EQUIVALENT = 34855;
  public static final int TAG_JPEG_AC_TABLES = 521;
  public static final int TAG_JPEG_DC_TABLES = 520;
  public static final int TAG_JPEG_LOSSLESS_PREDICTORS = 517;
  public static final int TAG_JPEG_POINT_TRANSFORMS = 518;
  public static final int TAG_JPEG_PROC = 512;
  public static final int TAG_JPEG_Q_TABLES = 519;
  public static final int TAG_JPEG_RESTART_INTERVAL = 515;
  public static final int TAG_JPEG_TABLES = 347;
  public static final int TAG_LENS = 65002;
  public static final int TAG_LENS_MAKE = 42035;
  public static final int TAG_LENS_MODEL = 42036;
  public static final int TAG_LENS_SERIAL_NUMBER = 42037;
  public static final int TAG_LENS_SPECIFICATION = 42034;
  @Deprecated
  public static final int TAG_LIGHT_SOURCE = 37384;
  public static final int TAG_MAKE = 271;
  public static final int TAG_MAKERNOTE = 37500;
  public static final int TAG_MAX_APERTURE = 37381;
  public static final int TAG_MAX_SAMPLE_VALUE = 281;
  public static final int TAG_METERING_MODE = 37383;
  public static final int TAG_MIN_SAMPLE_VALUE = 280;
  public static final int TAG_MODEL = 272;
  public static final int TAG_NEW_SUBFILE_TYPE = 254;
  public static final int TAG_NOISE = 37389;
  public static final int TAG_OPTO_ELECTRIC_CONVERSION_FUNCTION = 34856;
  public static final int TAG_ORIENTATION = 274;
  public static final int TAG_PADDING = 59932;
  public static final int TAG_PAGE_NAME = 285;
  public static final int TAG_PAGE_NUMBER = 297;
  public static final int TAG_PANASONIC_TITLE = 50898;
  public static final int TAG_PANASONIC_TITLE_2 = 50899;
  public static final int TAG_PHOTOMETRIC_INTERPRETATION = 262;
  public static final int TAG_PLANAR_CONFIGURATION = 284;
  public static final int TAG_PREDICTOR = 317;
  public static final int TAG_PRIMARY_CHROMATICITIES = 319;
  public static final int TAG_PRINT_IMAGE_MATCHING_INFO = 50341;
  public static final int TAG_RATING = 18246;
  public static final int TAG_RECOMMENDED_EXPOSURE_INDEX = 34866;
  public static final int TAG_REFERENCE_BLACK_WHITE = 532;
  public static final int TAG_RELATED_IMAGE_FILE_FORMAT = 4096;
  public static final int TAG_RELATED_IMAGE_HEIGHT = 4098;
  public static final int TAG_RELATED_IMAGE_WIDTH = 4097;
  public static final int TAG_RELATED_SOUND_FILE = 40964;
  public static final int TAG_RESOLUTION_UNIT = 296;
  public static final int TAG_ROWS_PER_STRIP = 278;
  public static final int TAG_SAMPLES_PER_PIXEL = 277;
  public static final int TAG_SATURATION = 41993;
  public static final int TAG_SCENE_CAPTURE_TYPE = 41990;
  public static final int TAG_SCENE_TYPE = 41729;
  public static final int TAG_SECURITY_CLASSIFICATION = 37394;
  public static final int TAG_SELF_TIMER_MODE = 34859;
  public static final int TAG_SELF_TIMER_MODE_TIFF_EP = 34859;
  public static final int TAG_SENSING_METHOD = 41495;
  public static final int TAG_SENSITIVITY_TYPE = 34864;
  public static final int TAG_SHARPNESS = 41994;
  public static final int TAG_SHUTTER_SPEED = 37377;
  public static final int TAG_SOFTWARE = 305;
  public static final int TAG_SPATIAL_FREQ_RESPONSE = 41484;
  public static final int TAG_SPATIAL_FREQ_RESPONSE_TIFF_EP = 37388;
  public static final int TAG_SPECTRAL_SENSITIVITY = 34852;
  public static final int TAG_STANDARD_ID_TIFF_EP = 37398;
  public static final int TAG_STANDARD_OUTPUT_SENSITIVITY = 34865;
  public static final int TAG_STRIP_BYTE_COUNTS = 279;
  public static final int TAG_STRIP_OFFSETS = 273;
  public static final int TAG_STRIP_ROW_COUNTS = 559;
  public static final int TAG_SUBFILE_TYPE = 255;
  public static final int TAG_SUBJECT_DISTANCE = 37382;
  public static final int TAG_SUBJECT_DISTANCE_RANGE = 41996;
  public static final int TAG_SUBJECT_LOCATION = 41492;
  public static final int TAG_SUBJECT_LOCATION_TIFF_EP = 37396;
  public static final int TAG_SUBSECOND_TIME = 37520;
  public static final int TAG_SUBSECOND_TIME_DIGITIZED = 37522;
  public static final int TAG_SUBSECOND_TIME_ORIGINAL = 37521;
  public static final int TAG_SUB_IFD_OFFSET = 330;
  public static final int TAG_THRESHOLDING = 263;
  public static final int TAG_TILE_BYTE_COUNTS = 325;
  public static final int TAG_TILE_LENGTH = 323;
  public static final int TAG_TILE_OFFSETS = 324;
  public static final int TAG_TILE_WIDTH = 322;
  public static final int TAG_TIME_ZONE_OFFSET = 34858;
  public static final int TAG_TIME_ZONE_OFFSET_TIFF_EP = 34858;
  public static final int TAG_TRANSFER_FUNCTION = 301;
  public static final int TAG_TRANSFER_RANGE = 342;
  public static final int TAG_USER_COMMENT = 37510;
  public static final int TAG_WHITE_BALANCE = 37384;
  public static final int TAG_WHITE_BALANCE_MODE = 41987;
  public static final int TAG_WHITE_POINT = 318;
  public static final int TAG_WIN_AUTHOR = 40093;
  public static final int TAG_WIN_COMMENT = 40092;
  public static final int TAG_WIN_KEYWORDS = 40094;
  public static final int TAG_WIN_SUBJECT = 40095;
  public static final int TAG_WIN_TITLE = 40091;
  public static final int TAG_X_RESOLUTION = 282;
  public static final int TAG_YCBCR_COEFFICIENTS = 529;
  public static final int TAG_YCBCR_POSITIONING = 531;
  public static final int TAG_YCBCR_SUBSAMPLING = 530;
  public static final int TAG_Y_RESOLUTION = 283;
  
  protected static void addExifTagNames(HashMap<Integer, String> paramHashMap)
  {
    paramHashMap.put(Integer.valueOf(1), "Interoperability Index");
    paramHashMap.put(Integer.valueOf(2), "Interoperability Version");
    paramHashMap.put(Integer.valueOf(254), "New Subfile Type");
    paramHashMap.put(Integer.valueOf(255), "Subfile Type");
    paramHashMap.put(Integer.valueOf(256), "Image Width");
    paramHashMap.put(Integer.valueOf(257), "Image Height");
    paramHashMap.put(Integer.valueOf(258), "Bits Per Sample");
    paramHashMap.put(Integer.valueOf(259), "Compression");
    paramHashMap.put(Integer.valueOf(262), "Photometric Interpretation");
    paramHashMap.put(Integer.valueOf(263), "Thresholding");
    paramHashMap.put(Integer.valueOf(266), "Fill Order");
    paramHashMap.put(Integer.valueOf(269), "Document Name");
    paramHashMap.put(Integer.valueOf(270), "Image Description");
    paramHashMap.put(Integer.valueOf(271), "Make");
    paramHashMap.put(Integer.valueOf(272), "Model");
    paramHashMap.put(Integer.valueOf(273), "Strip Offsets");
    paramHashMap.put(Integer.valueOf(274), "Orientation");
    paramHashMap.put(Integer.valueOf(277), "Samples Per Pixel");
    paramHashMap.put(Integer.valueOf(278), "Rows Per Strip");
    paramHashMap.put(Integer.valueOf(279), "Strip Byte Counts");
    paramHashMap.put(Integer.valueOf(280), "Minimum Sample Value");
    paramHashMap.put(Integer.valueOf(281), "Maximum Sample Value");
    paramHashMap.put(Integer.valueOf(282), "X Resolution");
    paramHashMap.put(Integer.valueOf(283), "Y Resolution");
    paramHashMap.put(Integer.valueOf(284), "Planar Configuration");
    paramHashMap.put(Integer.valueOf(285), "Page Name");
    paramHashMap.put(Integer.valueOf(296), "Resolution Unit");
    paramHashMap.put(Integer.valueOf(297), "Page Number");
    paramHashMap.put(Integer.valueOf(301), "Transfer Function");
    paramHashMap.put(Integer.valueOf(305), "Software");
    paramHashMap.put(Integer.valueOf(306), "Date/Time");
    paramHashMap.put(Integer.valueOf(315), "Artist");
    paramHashMap.put(Integer.valueOf(317), "Predictor");
    paramHashMap.put(Integer.valueOf(316), "Host Computer");
    paramHashMap.put(Integer.valueOf(318), "White Point");
    paramHashMap.put(Integer.valueOf(319), "Primary Chromaticities");
    paramHashMap.put(Integer.valueOf(322), "Tile Width");
    paramHashMap.put(Integer.valueOf(323), "Tile Length");
    paramHashMap.put(Integer.valueOf(324), "Tile Offsets");
    paramHashMap.put(Integer.valueOf(325), "Tile Byte Counts");
    paramHashMap.put(Integer.valueOf(330), "Sub IFD Pointer(s)");
    paramHashMap.put(Integer.valueOf(342), "Transfer Range");
    paramHashMap.put(Integer.valueOf(347), "JPEG Tables");
    paramHashMap.put(Integer.valueOf(512), "JPEG Proc");
    paramHashMap.put(Integer.valueOf(515), "JPEG Restart Interval");
    paramHashMap.put(Integer.valueOf(517), "JPEG Lossless Predictors");
    paramHashMap.put(Integer.valueOf(518), "JPEG Point Transforms");
    paramHashMap.put(Integer.valueOf(519), "JPEGQ Tables");
    paramHashMap.put(Integer.valueOf(520), "JPEGDC Tables");
    paramHashMap.put(Integer.valueOf(521), "JPEGAC Tables");
    paramHashMap.put(Integer.valueOf(529), "YCbCr Coefficients");
    paramHashMap.put(Integer.valueOf(530), "YCbCr Sub-Sampling");
    paramHashMap.put(Integer.valueOf(531), "YCbCr Positioning");
    paramHashMap.put(Integer.valueOf(532), "Reference Black/White");
    paramHashMap.put(Integer.valueOf(559), "Strip Row Counts");
    paramHashMap.put(Integer.valueOf(700), "Application Notes");
    paramHashMap.put(Integer.valueOf(4096), "Related Image File Format");
    paramHashMap.put(Integer.valueOf(4097), "Related Image Width");
    paramHashMap.put(Integer.valueOf(4098), "Related Image Height");
    paramHashMap.put(Integer.valueOf(18246), "Rating");
    paramHashMap.put(Integer.valueOf(33421), "CFA Repeat Pattern Dim");
    paramHashMap.put(Integer.valueOf(33422), "CFA Pattern");
    paramHashMap.put(Integer.valueOf(33423), "Battery Level");
    paramHashMap.put(Integer.valueOf(33432), "Copyright");
    paramHashMap.put(Integer.valueOf(33434), "Exposure Time");
    paramHashMap.put(Integer.valueOf(33437), "F-Number");
    paramHashMap.put(Integer.valueOf(33723), "IPTC/NAA");
    paramHashMap.put(Integer.valueOf(34675), "Inter Color Profile");
    paramHashMap.put(Integer.valueOf(34850), "Exposure Program");
    paramHashMap.put(Integer.valueOf(34852), "Spectral Sensitivity");
    paramHashMap.put(Integer.valueOf(34855), "ISO Speed Ratings");
    paramHashMap.put(Integer.valueOf(34856), "Opto-electric Conversion Function (OECF)");
    paramHashMap.put(Integer.valueOf(34857), "Interlace");
    Integer localInteger1 = Integer.valueOf(34858);
    paramHashMap.put(localInteger1, "Time Zone Offset");
    Integer localInteger2 = Integer.valueOf(34859);
    paramHashMap.put(localInteger2, "Self Timer Mode");
    paramHashMap.put(Integer.valueOf(34864), "Sensitivity Type");
    paramHashMap.put(Integer.valueOf(34865), "Standard Output Sensitivity");
    paramHashMap.put(Integer.valueOf(34866), "Recommended Exposure Index");
    paramHashMap.put(localInteger1, "Time Zone Offset");
    paramHashMap.put(localInteger2, "Self Timer Mode");
    paramHashMap.put(Integer.valueOf(36864), "Exif Version");
    paramHashMap.put(Integer.valueOf(36867), "Date/Time Original");
    paramHashMap.put(Integer.valueOf(36868), "Date/Time Digitized");
    paramHashMap.put(Integer.valueOf(37121), "Components Configuration");
    paramHashMap.put(Integer.valueOf(37122), "Compressed Bits Per Pixel");
    paramHashMap.put(Integer.valueOf(37377), "Shutter Speed Value");
    paramHashMap.put(Integer.valueOf(37378), "Aperture Value");
    paramHashMap.put(Integer.valueOf(37379), "Brightness Value");
    paramHashMap.put(Integer.valueOf(37380), "Exposure Bias Value");
    paramHashMap.put(Integer.valueOf(37381), "Max Aperture Value");
    paramHashMap.put(Integer.valueOf(37382), "Subject Distance");
    paramHashMap.put(Integer.valueOf(37383), "Metering Mode");
    paramHashMap.put(Integer.valueOf(37384), "White Balance");
    paramHashMap.put(Integer.valueOf(37385), "Flash");
    paramHashMap.put(Integer.valueOf(37386), "Focal Length");
    paramHashMap.put(Integer.valueOf(37387), "Flash Energy");
    paramHashMap.put(Integer.valueOf(37388), "Spatial Frequency Response");
    paramHashMap.put(Integer.valueOf(37389), "Noise");
    paramHashMap.put(Integer.valueOf(37390), "Focal Plane X Resolution");
    paramHashMap.put(Integer.valueOf(37391), "Focal Plane Y Resolution");
    paramHashMap.put(Integer.valueOf(37393), "Image Number");
    paramHashMap.put(Integer.valueOf(37394), "Security Classification");
    paramHashMap.put(Integer.valueOf(37395), "Image History");
    paramHashMap.put(Integer.valueOf(37396), "Subject Location");
    paramHashMap.put(Integer.valueOf(37397), "Exposure Index");
    paramHashMap.put(Integer.valueOf(37398), "TIFF/EP Standard ID");
    paramHashMap.put(Integer.valueOf(37500), "Makernote");
    paramHashMap.put(Integer.valueOf(37510), "User Comment");
    paramHashMap.put(Integer.valueOf(37520), "Sub-Sec Time");
    paramHashMap.put(Integer.valueOf(37521), "Sub-Sec Time Original");
    paramHashMap.put(Integer.valueOf(37522), "Sub-Sec Time Digitized");
    paramHashMap.put(Integer.valueOf(40091), "Windows XP Title");
    paramHashMap.put(Integer.valueOf(40092), "Windows XP Comment");
    paramHashMap.put(Integer.valueOf(40093), "Windows XP Author");
    paramHashMap.put(Integer.valueOf(40094), "Windows XP Keywords");
    paramHashMap.put(Integer.valueOf(40095), "Windows XP Subject");
    paramHashMap.put(Integer.valueOf(40960), "FlashPix Version");
    paramHashMap.put(Integer.valueOf(40961), "Color Space");
    paramHashMap.put(Integer.valueOf(40962), "Exif Image Width");
    paramHashMap.put(Integer.valueOf(40963), "Exif Image Height");
    paramHashMap.put(Integer.valueOf(40964), "Related Sound File");
    paramHashMap.put(Integer.valueOf(41483), "Flash Energy");
    paramHashMap.put(Integer.valueOf(41484), "Spatial Frequency Response");
    paramHashMap.put(Integer.valueOf(41486), "Focal Plane X Resolution");
    paramHashMap.put(Integer.valueOf(41487), "Focal Plane Y Resolution");
    paramHashMap.put(Integer.valueOf(41488), "Focal Plane Resolution Unit");
    paramHashMap.put(Integer.valueOf(41492), "Subject Location");
    paramHashMap.put(Integer.valueOf(41493), "Exposure Index");
    paramHashMap.put(Integer.valueOf(41495), "Sensing Method");
    paramHashMap.put(Integer.valueOf(41728), "File Source");
    paramHashMap.put(Integer.valueOf(41729), "Scene Type");
    paramHashMap.put(Integer.valueOf(41730), "CFA Pattern");
    paramHashMap.put(Integer.valueOf(41985), "Custom Rendered");
    paramHashMap.put(Integer.valueOf(41986), "Exposure Mode");
    paramHashMap.put(Integer.valueOf(41987), "White Balance Mode");
    paramHashMap.put(Integer.valueOf(41988), "Digital Zoom Ratio");
    paramHashMap.put(Integer.valueOf(41989), "Focal Length 35");
    paramHashMap.put(Integer.valueOf(41990), "Scene Capture Type");
    paramHashMap.put(Integer.valueOf(41991), "Gain Control");
    paramHashMap.put(Integer.valueOf(41992), "Contrast");
    paramHashMap.put(Integer.valueOf(41993), "Saturation");
    paramHashMap.put(Integer.valueOf(41994), "Sharpness");
    paramHashMap.put(Integer.valueOf(41995), "Device Setting Description");
    paramHashMap.put(Integer.valueOf(41996), "Subject Distance Range");
    paramHashMap.put(Integer.valueOf(42016), "Unique Image ID");
    paramHashMap.put(Integer.valueOf(42032), "Camera Owner Name");
    paramHashMap.put(Integer.valueOf(42033), "Body Serial Number");
    paramHashMap.put(Integer.valueOf(42034), "Lens Specification");
    paramHashMap.put(Integer.valueOf(42035), "Lens Make");
    paramHashMap.put(Integer.valueOf(42036), "Lens Model");
    paramHashMap.put(Integer.valueOf(42037), "Lens Serial Number");
    paramHashMap.put(Integer.valueOf(42240), "Gamma");
    paramHashMap.put(Integer.valueOf(50341), "Print Image Matching (PIM) Info");
    paramHashMap.put(Integer.valueOf(50898), "Panasonic Title");
    paramHashMap.put(Integer.valueOf(50899), "Panasonic Title (2)");
    paramHashMap.put(Integer.valueOf(59932), "Padding");
    paramHashMap.put(Integer.valueOf(65002), "Lens");
  }
}


/* Location:              C:\Users\adinb\Downloads\dex2jar-2.0\dex2jar-2.0\0x89a2c000-dex2jar.jar!\com\drew\metadata\exif\ExifDirectoryBase.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */