package lecho.lib.hellocharts.formatter;

import lecho.lib.hellocharts.model.AxisValue;

public abstract interface AxisValueFormatter
{
  public abstract int formatValueForAutoGeneratedAxis(char[] paramArrayOfChar, float paramFloat, int paramInt);
  
  public abstract int formatValueForManualAxis(char[] paramArrayOfChar, AxisValue paramAxisValue);
}


/* Location:              C:\Users\adinb\Downloads\dex2jar-2.0\dex2jar-2.0\0x87b1d00c-dex2jar.jar!\lecho\lib\hellocharts\formatter\AxisValueFormatter.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */