package lecho.lib.hellocharts.formatter;

import lecho.lib.hellocharts.model.AxisValue;

public class SimpleAxisValueFormatter
  implements AxisValueFormatter
{
  private ValueFormatterHelper valueFormatterHelper;
  
  public SimpleAxisValueFormatter()
  {
    ValueFormatterHelper localValueFormatterHelper = new ValueFormatterHelper();
    this.valueFormatterHelper = localValueFormatterHelper;
    localValueFormatterHelper.determineDecimalSeparator();
  }
  
  public SimpleAxisValueFormatter(int paramInt)
  {
    this();
    this.valueFormatterHelper.setDecimalDigitsNumber(paramInt);
  }
  
  public int formatValueForAutoGeneratedAxis(char[] paramArrayOfChar, float paramFloat, int paramInt)
  {
    return this.valueFormatterHelper.formatFloatValueWithPrependedAndAppendedText(paramArrayOfChar, paramFloat, paramInt);
  }
  
  public int formatValueForManualAxis(char[] paramArrayOfChar, AxisValue paramAxisValue)
  {
    return 0;
  }
  
  public char[] getAppendedText()
  {
    return this.valueFormatterHelper.getAppendedText();
  }
  
  public int getDecimalDigitsNumber()
  {
    return this.valueFormatterHelper.getDecimalDigitsNumber();
  }
  
  public char getDecimalSeparator()
  {
    return this.valueFormatterHelper.getDecimalSeparator();
  }
  
  public char[] getPrependedText()
  {
    return this.valueFormatterHelper.getPrependedText();
  }
  
  public SimpleAxisValueFormatter setAppendedText(char[] paramArrayOfChar)
  {
    this.valueFormatterHelper.setAppendedText(paramArrayOfChar);
    return this;
  }
  
  public SimpleAxisValueFormatter setDecimalDigitsNumber(int paramInt)
  {
    this.valueFormatterHelper.setDecimalDigitsNumber(paramInt);
    return this;
  }
  
  public SimpleAxisValueFormatter setDecimalSeparator(char paramChar)
  {
    this.valueFormatterHelper.setDecimalSeparator(paramChar);
    return this;
  }
  
  public SimpleAxisValueFormatter setPrependedText(char[] paramArrayOfChar)
  {
    this.valueFormatterHelper.setPrependedText(paramArrayOfChar);
    return this;
  }
}


/* Location:              C:\Users\adinb\Downloads\dex2jar-2.0\dex2jar-2.0\0x87b1d00c-dex2jar.jar!\lecho\lib\hellocharts\formatter\SimpleAxisValueFormatter.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */