package dji.sdksharedlib.util.configuration.keymaps;

import dji.midware.data.params.P3.ParamCfgName;
import dji.sdksharedlib.hardware.abstractions.DJISDKCacheUpdateType;
import dji.sdksharedlib.util.configuration.DJISDKCacheProductConfigsKey;
import dji.sdksharedlib.util.configuration.DJISDKCacheProductConfigsKey.Builder;
import java.util.HashMap;

public class FlightControllerConfigsKeyMap
  implements ParamCfgName
{
  public static HashMap<String, DJISDKCacheProductConfigsKey> getFlightControllerConfigsKeyMap()
  {
    DJISDKCacheProductConfigsKey.Builder localBuilder = new DJISDKCacheProductConfigsKey.Builder();
    HashMap localHashMap = new HashMap();
    Object localObject1 = localBuilder.dataSize(2);
    Integer localInteger1 = Integer.valueOf(10);
    localHashMap.put("FlightControllerConfigAttitudeRange", ((DJISDKCacheProductConfigsKey.Builder)localObject1).minValue(localInteger1).maxValue(Integer.valueOf(60)).defaultValue(Integer.valueOf(35)).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigAttitudeRange").keyHashName("g_config.control.atti_range_0").maxVersion(15).minVersion(-1).backupKey(null).dataType(Short.class).build());
    Object localObject2 = localBuilder.dataSize(2).minValue(Integer.valueOf(60)).maxValue(Integer.valueOf(300));
    localObject1 = Integer.valueOf(150);
    localHashMap.put("FlightControllerConfigTorsionRate", ((DJISDKCacheProductConfigsKey.Builder)localObject2).defaultValue((Number)localObject1).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigTorsionRate").keyHashName("g_config.control.atti_torsion_w_rate_0").maxVersion(15).minVersion(-1).backupKey("FlightControllerConfigTorsionGyroRange").dataType(Short.class).build());
    Object localObject3 = localBuilder.dataSize(4);
    localObject2 = Integer.valueOf(50);
    localHashMap.put("FlightControllerConfigYawAtSport", ((DJISDKCacheProductConfigsKey.Builder)localObject3).minValue((Number)localObject2).maxValue(Integer.valueOf(250)).defaultValue((Number)localObject1).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigYawAtSport").keyHashName("g_config.mode_sport_cfg.tors_gyro_range_0").minVersion(18).maxVersion(-1).backupKey(null).dataType(Float.class).build());
    localObject3 = localBuilder.dataSize(2);
    Integer localInteger2 = Integer.valueOf(20);
    Object localObject4 = ((DJISDKCacheProductConfigsKey.Builder)localObject3).minValue(localInteger2).maxValue(Integer.valueOf(100)).defaultValue((Number)localObject2).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigRcTiltSensitive").keyHashName("g_config.control.rc_tilt_sensitivity_0").maxVersion(-1);
    localObject3 = Integer.valueOf(0);
    localHashMap.put("FlightControllerConfigRcTiltSensitive", ((DJISDKCacheProductConfigsKey.Builder)localObject4).minVersion(0).backupKey("FlightControllerConfigTiltSensitive").dataType(Short.class).build());
    Object localObject5 = localBuilder.dataSize(2);
    localObject4 = Integer.valueOf(70);
    Object localObject6 = ((DJISDKCacheProductConfigsKey.Builder)localObject5).minValue((Number)localObject4);
    localObject5 = Integer.valueOf(130);
    localHashMap.put("FlightControllerConfigBrakeSensitive", ((DJISDKCacheProductConfigsKey.Builder)localObject6).maxValue((Number)localObject5).defaultValue(Integer.valueOf(-1)).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigBrakeSensitive").keyHashName("g_config.control.brake_sensitivity_0").maxVersion(-1).minVersion(0).backupKey(null).dataType(Short.class).build());
    localHashMap.put("FlightControllerConfigTorsionGyroRange", localBuilder.dataSize(4).minValue(localInteger1).maxValue(Integer.valueOf(1000)).defaultValue((Number)localObject1).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigTorsionGyroRange").keyHashName("g_config.mode_normal_cfg.tors_gyro_range_0").maxVersion(-1).minVersion(16).backupKey(null).dataType(Float.class).build());
    Object localObject7 = localBuilder.dataSize(2).minValue(localInteger2);
    localObject6 = Integer.valueOf(80);
    localObject7 = ((DJISDKCacheProductConfigsKey.Builder)localObject7).maxValue((Number)localObject6);
    Object localObject8 = Integer.valueOf(40);
    localHashMap.put("FlightControllerConfigThrottleExperienceMidPoint", ((DJISDKCacheProductConfigsKey.Builder)localObject7).defaultValue((Number)localObject8).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigThrottleExperienceMidPoint").keyHashName("g_config.control.thr_exp_mid_point_0").maxVersion(15).minVersion(-1).backupKey("FlightControllerConfigNormalLiftExpMiddlePoint").dataType(Short.class).build());
    localHashMap.put("FlightControllerConfigTiltExperienceMidPoint", localBuilder.dataSize(2).minValue(localInteger2).maxValue((Number)localObject6).defaultValue((Number)localObject8).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigTiltExperienceMidPoint").keyHashName("g_config.control.tilt_exp_mid_point_0").maxVersion(15).minVersion(-1).backupKey("FlightControllerConfigNormalTiltExpMiddlePoint").dataType(Short.class).build());
    localHashMap.put("FlightControllerConfigYawExperienceMidPoint", localBuilder.dataSize(2).minValue(localInteger2).maxValue((Number)localObject6).defaultValue((Number)localObject8).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigYawExperienceMidPoint").keyHashName("g_config.control.yaw_exp_mid_point_0").maxVersion(15).minVersion(-1).backupKey("FlightControllerConfigNormalTorsionExpMiddlePoint").dataType(Short.class).build());
    localHashMap.put("FlightControllerConfigSportThrottleExperienceMidPoint", localBuilder.dataSize(4).minValue(localInteger2).maxValue((Number)localObject6).defaultValue((Number)localObject8).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigSportThrottleExperienceMidPoint").keyHashName("g_config.sport_cfg.thr_exp_mid_point_0").maxVersion(15).minVersion(11).backupKey("FlightControllerConfigSportLiftExpMiddlePoint").dataType(Float.class).build());
    localHashMap.put("FlightControllerConfigSportTiltExperienceMidPoint", localBuilder.dataSize(4).minValue(localInteger2).maxValue((Number)localObject6).defaultValue((Number)localObject8).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigSportTiltExperienceMidPoint").keyHashName("g_config.sport_cfg.tilt_exp_mid_point_0").maxVersion(15).minVersion(11).backupKey("FlightControllerConfigSportTiltExpMiddlePoint").dataType(Float.class).build());
    localHashMap.put("FlightControllerConfigSportYawExperienceMidPoint", localBuilder.dataSize(4).minValue(localInteger2).maxValue((Number)localObject6).defaultValue((Number)localObject8).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigSportYawExperienceMidPoint").keyHashName("g_config.sport_cfg.yaw_exp_mid_point_0").maxVersion(15).minVersion(11).backupKey("FlightControllerConfigSportTorsionExpMiddlePoint").dataType(Float.class).build());
    localInteger2 = Integer.valueOf(1);
    localHashMap.put("FlightControllerConfigImuTempRealCtlOutPer", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(Integer.valueOf(255)).defaultValue((Number)localObject3).accessMask(1).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigImuTempRealCtlOutPer").keyHashName("imu_temp.real_ctl_out_per_0").maxVersion(15).minVersion(-1).backupKey(null).dataType(Short.class).build());
    localObject7 = localBuilder.dataSize(4);
    localObject6 = Double.valueOf(0.1D);
    localObject8 = ((DJISDKCacheProductConfigsKey.Builder)localObject7).minValue((Number)localObject6);
    localObject7 = Double.valueOf(0.9D);
    localObject8 = ((DJISDKCacheProductConfigsKey.Builder)localObject8).maxValue((Number)localObject7);
    Double localDouble = Double.valueOf(0.5D);
    localHashMap.put("FlightControllerConfigGentleTiltExpMiddlePoint", ((DJISDKCacheProductConfigsKey.Builder)localObject8).defaultValue(localDouble).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigGentleTiltExpMiddlePoint").keyHashName("g_config.mode_gentle_cfg.tilt_exp_mid_point_0").maxVersion(-1).minVersion(16).backupKey(null).dataType(Float.class).build());
    localHashMap.put("FlightControllerConfigGentleTorsionExpMiddlePoint", localBuilder.dataSize(4).minValue((Number)localObject6).maxValue((Number)localObject7).defaultValue(localDouble).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigGentleTorsionExpMiddlePoint").keyHashName("g_config.mode_gentle_cfg.tors_exp_mid_point_0").maxVersion(-1).minVersion(16).backupKey(null).dataType(Float.class).build());
    localHashMap.put("FlightControllerConfigGentleLiftExpMiddlePoint", localBuilder.dataSize(4).minValue((Number)localObject6).maxValue((Number)localObject7).defaultValue(localDouble).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigGentleLiftExpMiddlePoint").keyHashName("g_config.mode_gentle_cfg.lift_exp_mid_point_0").maxVersion(-1).minVersion(16).backupKey(null).dataType(Float.class).build());
    localHashMap.put("FlightControllerConfigNormalTiltExpMiddlePoint", localBuilder.dataSize(4).minValue((Number)localObject6).maxValue((Number)localObject7).defaultValue(localDouble).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigGentleTiltExpMiddlePoint").keyHashName("g_config.mode_normal_cfg.tilt_exp_mid_point_0").maxVersion(-1).minVersion(16).backupKey(null).dataType(Float.class).build());
    localHashMap.put("FlightControllerConfigNormalTorsionExpMiddlePoint", localBuilder.dataSize(4).minValue((Number)localObject6).maxValue((Number)localObject7).defaultValue(localDouble).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigNormalTorsionExpMiddlePoint").keyHashName("g_config.mode_normal_cfg.tors_exp_mid_point_0").maxVersion(-1).minVersion(16).backupKey(null).dataType(Float.class).build());
    localHashMap.put("FlightControllerConfigNormalLiftExpMiddlePoint", localBuilder.dataSize(4).minValue((Number)localObject6).maxValue((Number)localObject7).defaultValue(localDouble).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigNormalLiftExpMiddlePoint").keyHashName("g_config.mode_normal_cfg.lift_exp_mid_point_0").maxVersion(-1).minVersion(16).backupKey(null).dataType(Float.class).build());
    localHashMap.put("FlightControllerConfigSportTiltExpMiddlePoint", localBuilder.dataSize(4).minValue((Number)localObject6).maxValue((Number)localObject7).defaultValue(localDouble).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigSportTiltExpMiddlePoint").keyHashName("g_config.mode_sport_cfg.tilt_exp_mid_point_0").maxVersion(-1).minVersion(16).backupKey(null).dataType(Float.class).build());
    localHashMap.put("FlightControllerConfigSportTorsionExpMiddlePoint", localBuilder.dataSize(4).minValue((Number)localObject6).maxValue((Number)localObject7).defaultValue(localDouble).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigSportTorsionExpMiddlePoint").keyHashName("g_config.mode_sport_cfg.tors_exp_mid_point_0").maxVersion(-1).minVersion(16).backupKey(null).dataType(Float.class).build());
    localHashMap.put("FlightControllerConfigSportLiftExpMiddlePoint", localBuilder.dataSize(4).minValue((Number)localObject6).maxValue((Number)localObject7).defaultValue(localDouble).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigSportLiftExpMiddlePoint").keyHashName("g_config.mode_sport_cfg.lift_exp_mid_point_0").maxVersion(-1).minVersion(16).backupKey(null).dataType(Float.class).build());
    localHashMap.put("FlightControllerConfigVerticalAtti", localBuilder.dataSize(2).minValue((Number)localObject4).maxValue((Number)localObject5).defaultValue(Integer.valueOf(75)).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigVerticalAtti").keyHashName("g_config.control.atti_vertical_0").maxVersion(-1).minVersion(0).backupKey(null).dataType(Short.class).build());
    localHashMap.put("FlightControllerConfigBasicPitch", localBuilder.dataSize(2).minValue((Number)localObject4).maxValue((Number)localObject5).defaultValue(Integer.valueOf(100)).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigBasicPitch").keyHashName("g_config.control.basic_pitch_0").maxVersion(-1).minVersion(0).backupKey(null).dataType(Short.class).build());
    localHashMap.put("FlightControllerConfigBasicRoll", localBuilder.dataSize(2).minValue((Number)localObject4).maxValue((Number)localObject5).defaultValue(Integer.valueOf(100)).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigBasicRoll").keyHashName("g_config.control.basic_roll_0").maxVersion(-1).minVersion(0).backupKey(null).dataType(Short.class).build());
    localHashMap.put("FlightControllerConfigBasicYaw", localBuilder.dataSize(2).minValue((Number)localObject4).maxValue((Number)localObject5).defaultValue(Integer.valueOf(100)).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigBasicYaw").keyHashName("g_config.control.basic_yaw_0").maxVersion(-1).minVersion(0).backupKey(null).dataType(Short.class).build());
    localHashMap.put("FlightControllerConfigBasicTail", localBuilder.dataSize(2).minValue((Number)localObject4).maxValue((Number)localObject5).defaultValue(Integer.valueOf(75)).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigBasicTail").keyHashName("g_config.control.basic_tail_0").maxVersion(-1).minVersion(0).backupKey(null).dataType(Short.class).build());
    localHashMap.put("AutoLandingGear", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(localInteger2).defaultValue((Number)localObject3).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("AutoLandingGear").keyHashName("g_config.gear_cfg.auto_control_enable_0").maxVersion(-1).minVersion(0).backupKey(null).dataType(Short.class).build());
    localHashMap.put("QuickSpin", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(localInteger2).defaultValue((Number)localObject3).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("QuickSpin").keyHashName("g_config.gear_cfg.auto_control_enable_0").maxVersion(-1).minVersion(0).backupKey(null).dataType(Short.class).build());
    localHashMap.put("AutoLandingGearGroundNotify", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(localInteger2).defaultValue((Number)localObject3).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("AutoLandingGearGroundNotify").keyHashName("g_config.gear_cfg.near_ground_reminder_0").maxVersion(-1).minVersion(0).backupKey(null).dataType(Short.class).build());
    localHashMap.put("RoofAvoidance", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(localInteger2).defaultValue((Number)localObject3).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("RoofAvoidance").keyHashName("g_config.flying_limit.roof_limit_enable_0").maxVersion(-1).minVersion(16).backupKey(null).dataType(Short.class).build());
    localHashMap.put("Tripod", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(localInteger2).defaultValue((Number)localObject3).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("Tripod").keyHashName("g_config.mode_tripod_en_cfg.tripod_func_enabled_0").maxVersion(-1).minVersion(16).backupKey(null).dataType(Short.class).build());
    localHashMap.put("PreciseLandingEnabled", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(localInteger2).defaultValue((Number)localObject3).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("PreciseLandingEnabled").keyHashName("g_config.landing.adv_landing_enable_0").maxVersion(-1).minVersion(16).backupKey(null).dataType(Short.class).build());
    localHashMap.put("AdvancedGoHomeEnabled", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(localInteger2).defaultValue((Number)localObject3).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("AdvancedGoHomeEnabled").keyHashName("g_config.go_home.adv_gohome_enable_0").maxVersion(-1).minVersion(16).backupKey(null).dataType(Short.class).build());
    localHashMap.put("FlightControllerConfigOnGroundHideGear", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(Integer.valueOf(255)).defaultValue((Number)localObject3).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigOnGroundHideGear").keyHashName("g_config.gear_cfg.on_ground_hide_gear_en_0").maxVersion(15).minVersion(0).backupKey("FlightControllerConfigHideGear").dataType(Integer.class).build());
    localHashMap.put("FlightControllerConfigHideGear", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(Integer.valueOf(255)).defaultValue((Number)localObject3).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigHideGear").keyHashName("g_config.gear_cfg.hide_gear_en_0").maxVersion(-1).minVersion(16).backupKey(null).dataType(Integer.class).build());
    localHashMap.put("FlightControllerConfigLandingCheckSwitch", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(localInteger2).defaultValue((Number)localObject3).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigLandingCheckSwitch").keyHashName("g_config.flying_limit.avoid_ground_and_smart_landing_enable_0").maxVersion(-1).minVersion(16).backupKey(null).dataType(Short.class).build());
    localHashMap.put("MaxDiveSpeed", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(Integer.valueOf(5)).defaultValue((Number)localObject3).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("MaxDiveSpeed").keyHashName("g_config.control.vert_vel_down_adding_0").maxVersion(-1).minVersion(18).backupKey(null).dataType(Short.class).build());
    localHashMap.put("FlightControllerConfigTripodRcScale", localBuilder.dataSize(4).minValue(Float.valueOf(10.0F)).maxValue(Float.valueOf(100.0F)).defaultValue(Float.valueOf(50.0F)).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigTripodRcScale").keyHashName("g_config.mode_tripod_cfg.rc_scale_0").maxVersion(-1).minVersion(21).backupKey(null).dataType(Float.class).build());
    localHashMap.put("FlightControllerConfigTripodGyroRange", localBuilder.dataSize(4).minValue(Float.valueOf(10.0F)).maxValue(Float.valueOf(90.0F)).defaultValue(Float.valueOf(50.0F)).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigTripodGyroRange").keyHashName("g_config.mode_tripod_cfg.tors_gyro_range_0").maxVersion(-1).minVersion(21).backupKey(null).dataType(Float.class).build());
    localHashMap.put("FlightControllerConfigTripodVertUp", localBuilder.dataSize(4).minValue(Float.valueOf(0.5F)).maxValue(Float.valueOf(3.0F)).defaultValue(Float.valueOf(0.5F)).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigTripodVertUp").keyHashName("g_config.mode_tripod_cfg.vert_vel_up_0").maxVersion(-1).minVersion(21).backupKey(null).dataType(Float.class).build());
    localHashMap.put("FlightControllerConfigTripodVertDown", localBuilder.dataSize(4).minValue(Float.valueOf(-0.3F)).maxValue(Float.valueOf(-0.5F)).defaultValue(Float.valueOf(-0.3F)).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FlightControllerConfigTripodVertDown").keyHashName("g_config.mode_tripod_cfg.vert_vel_down_0").maxVersion(-1).minVersion(21).backupKey(null).dataType(Float.class).build());
    localHashMap.put("CinematicModeGain", localBuilder.dataSize(4).minValue(localInteger1).maxValue((Number)localObject1).defaultValue(localInteger1).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("CinematicModeGain").keyHashName("CM_brake_sensitive_0").maxVersion(-1).minVersion(21).backupKey(null).dataType(Short.class).build());
    localHashMap.put("CinematicCourseAngularVelocityRange", localBuilder.dataSize(4).minValue(Float.valueOf(50.0F)).maxValue(Float.valueOf(250.0F)).defaultValue(Float.valueOf(50.0F)).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("CinematicCourseAngularVelocityRange").keyHashName("CM_tors_range_0").maxVersion(-1).minVersion(21).backupKey(null).dataType(Float.class).build());
    localHashMap.put("FanEnabled", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(localInteger2).defaultValue((Number)localObject3).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("FanEnabled").keyHashName("g_config.mr_ctrl.prop_cover_en_0").maxVersion(-1).minVersion(21).backupKey(null).dataType(Integer.class).build());
    localHashMap.put("LandingProtectionEnabled", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(localInteger2).defaultValue((Number)localObject3).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("LandingProtectionEnabled").keyHashName("g_config.flying_limit.avoid_ground_and_smart_landing_enable_0").maxVersion(-1).minVersion(16).backupKey(null).dataType(Short.class).build());
    localHashMap.put("VisionPositioningEnabled", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(localInteger2).defaultValue((Number)localObject3).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("VisionPositioningEnabled").keyHashName("g_config.mvo_cfg.mvo_func_en_0").maxVersion(-1).minVersion(6).backupKey(null).dataType(Short.class).build());
    localHashMap.put("VisionGHAVoidEnabled", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(localInteger2).defaultValue((Number)localObject3).accessMask(7).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("VisionGHAVoidEnabled").keyHashName("g_config.go_home.avoid_enable_0").maxVersion(-1).minVersion(6).backupKey(null).dataType(Short.class).build());
    localHashMap.put("ActiveAvoidanceEnabled", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(localInteger2).defaultValue((Number)localObject3).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("ActiveAvoidanceEnabled").keyHashName("g_cfg_debug.overshot_enable_0").maxVersion(-1).minVersion(21).backupKey(null).dataType(Float.class).build());
    localHashMap.put("ConfigRcScaleInAvoidance", localBuilder.dataSize(4).minValue(Double.valueOf(0.3D)).maxValue(Double.valueOf(0.55D)).defaultValue(Double.valueOf(0.3D)).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("ConfigRcScaleInAvoidance").keyHashName("g_config.avoid_cfg.avoid_rc_scale_0").maxVersion(-1).minVersion(6).backupKey(null).dataType(Float.class).build());
    localHashMap.put("ConfigRcScaleInNormal", localBuilder.dataSize(4).minValue(Double.valueOf(0.55D)).maxValue(Double.valueOf(0.8D)).defaultValue(Double.valueOf(0.55D)).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("ConfigRcScaleInNormal").keyHashName("g_config.mode_normal_cfg.rc_scale_0").maxVersion(-1).minVersion(6).backupKey(null).dataType(Float.class).build());
    localHashMap.put("ConfigRcScaleInSport", localBuilder.dataSize(4).minValue(Double.valueOf(0.47D)).maxValue(Double.valueOf(0.8D)).defaultValue(Double.valueOf(0.47D)).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("ConfigRcScaleInSport").keyHashName("g_config.mode_sport_cfg.rc_scale_0").maxVersion(-1).minVersion(6).backupKey(null).dataType(Float.class).build());
    localHashMap.put("ConfigYawRateInAvoidance", localBuilder.dataSize(4).minValue((Number)localObject2).maxValue((Number)localObject4).defaultValue((Number)localObject2).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("ConfigYawRateInAvoidance").keyHashName("g_config.avoid_cfg.avoid_tors_rate_range_0").maxVersion(-1).minVersion(6).backupKey(null).dataType(Float.class).build());
    localHashMap.put("ConfigYawRateInNormal", localBuilder.dataSize(4).minValue((Number)localObject4).maxValue(Integer.valueOf(90)).defaultValue((Number)localObject4).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("ConfigYawRateInNormal").keyHashName("g_config.mode_normal_cfg.tors_gyro_range_0").maxVersion(-1).minVersion(6).backupKey(null).dataType(Float.class).build());
    localHashMap.put("ConfigYawRateInSport", localBuilder.dataSize(4).minValue(Integer.valueOf(90)).maxValue((Number)localObject1).defaultValue(Integer.valueOf(90)).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("ConfigYawRateInSport").keyHashName("g_config.mode_sport_cfg.tors_gyro_range_0").maxVersion(-1).minVersion(6).backupKey(null).dataType(Float.class).build());
    localHashMap.put("ConfigRTHInCurrentAltitude", localBuilder.dataSize(1).minValue((Number)localObject3).maxValue(localInteger2).defaultValue((Number)localObject3).accessMask(3).updateType(DJISDKCacheUpdateType.USER_DRIVEN).keyName("ConfigRTHInCurrentAltitude").keyHashName("g_config.go_home.cur_height_gohome_enable_0").maxVersion(-1).minVersion(6).backupKey(null).dataType(Integer.class).build());
    return localHashMap;
  }
}


/* Location:              C:\Users\adinb\Downloads\dex2jar-2.0\dex2jar-2.0\0x87b1d00c-dex2jar.jar!\dji\sdksharedli\\util\configuration\keymaps\FlightControllerConfigsKeyMap.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */